### ISSUE TITLE
create window command

### ISSUE THREAD

**Issue by Pascal-J** [martin-saurer/qjide#3]
There may be something I don't understand, but copying from documentation pdf: (typing in console)

  wwd 'create window aa';1000;400;'asdf'

gives 

|domain error: cut
|   cmd1=.    cut cmd0

looking at wwd_qjide_  code,

 wwd 'create window aa',&< 1000;400;'asdf'

would seem like the right way to pass the initial parsing test.  No error happens when I do this, but no window is created either.

**Comment by martin-saurer** [comment]
@Pascal-J Please try this:

wwd 'create window aa' ;< 1000;400;'asdf'
wwd 'set aa visible' ;< 'true'

You will receive an error message like:
   value error: aa_appear
because there is no event handler for <window-name>_appear defined.

But you should see the window as expected.

I have added some WWD examples to this repo.

Please let me know if it works for you.

**Comment by Pascal-J** [comment]
it works, for wd "compatibility/similarity"

      wwd2_qjide_ =: 3 : '0 0 $ wwdsend_qjide_ =: ''['' , '']'' ,~ enc_json@:(cut@:(0&{::) ;  <"1`{.@.(1=#)@}.) y'

this allows sending commands without the pre-division into 2 boxes.  I think your pdf document does not have the manual separation in its examples.

A minor issue is that in the editor window, spacebar does "not take" though it works in console window (firefox)

**Comment by martin-saurer** [comment]
@Pascal-J 
Thanks for wwd2_qjide_. I will give it a try as soon as time permits.

All the examples in the PDF are in the form:
wwd '<command-string>' ;< arg_1;arg_2;…;arg_n
On Page 5 or 8, for example. So I thought this is clear enough.

The spacebar works in the editor window. Unfortunately there is a still unresolved glitch with
the CodeMirror editor component and the qooxdoo frontend. If the spacebar doesn't work,
just click in J console with your mouse, and then click into your editor window. Scroll through
your source code only using the keyboard. When using the mouse wheel or the scroll bar,
the spacebar is dead again.

**Comment by martin-saurer** [comment]
Qjide will no longer be developed further. Sorry.
If time permits, there will be a J web IDE based on OpenUI5.
In the far, far future.
